### ISSUE TITLE
Exported SVG doesn't match original size

### ISSUE THREAD

**Issue by Mario662629** [photopea/vectorpea#78]
For some SVG files, when I fit to artwork bounds, it shows properly at first. However, when exported and then re-opened back in Vectorpea, the exported file has a few tiny gaps on two of the sides.

To see the bug in action (try this with each file):
- Save any of the SVG image files attached below to your device, then open them in Vectorpea.
- Below each image, there is a list of sides that the empty space appeared on for that image. Zoom in on those edges of the files in Vectorpea, and compare them to the other edges, the sides listed have empty space while the others have the image touch the edge of the artboard.
- Select Object > Fit to Artwork Bounds; the edges of the artboard should touch the edges of the image.
- Without editing the image any further, export it as SVG, then open the newly-exported SVG in Vectorpea; the gaps come back on the same sides mentioned for that image.

![Image](https://github.com/user-attachments/assets/fa75d6e7-4668-4063-ba70-f73634f8e637)
Has gaps on the bottom and right sides, leaving the image in the top-left.

![Image](https://github.com/user-attachments/assets/d15e4cd4-354e-4542-8e95-ab089b5dff19)
Has gaps on the bottom and right sides, leaving the image in the top-left.

![Image](https://github.com/user-attachments/assets/397320b4-916b-4a5b-87e8-39089af8afcc)
Has gaps on the top and right sides, leaving the image in the bottom-left.

![Image](https://github.com/user-attachments/assets/dc1c4431-e09d-4eba-a909-3dca0a8871ac)
Has gaps on the bottom and right sides, leaving the image in the top-left.

**Comment by photopea** [comment]
I think I have fixed it, could you try it again?

**Comment by Mario662629** [comment]
Looks like it's partially fixed; the image below create tiny gaps, but they appear either on the top and bottom, or on the left and right. And, the gaps aren't as large.

![Image](https://github.com/user-attachments/assets/09d8a3d6-429a-42c8-9591-cb0be2a04d89)

**Comment by photopea** [comment]
When you open that SVG file in Vectorpea or in Adobe Illustrator, there are gaps on the right and the bottom side, that is a correct behaviour. The content of your SVG is a bit smaller than the size of your SVG.

**Comment by Mario662629** [comment]
Oh, and by the way, the reason of this issue is the fact that I can't find the official diagrams for the Ontario road signs, unlike the U.S. MUTCD signs; I could only find the sign design pattern files (e.g. https://www.library.mto.gov.on.ca/SydneyPLUS/Sydney/Portal/default.aspx?component=AAAAIY&record=01770351-8895-4f48-a8b5-62a03145ae1c). On Wikimedia Commons (https://commons.wikimedia.org/wiki/Ontario_road_signs), some of the diagrams were not updated in 2019 or 2020.

From there, I was putting the PDFs in Vectorpea and exporting the signs, but there was some size disparity, and some of them had the gaps created on different sides. In this example, the selected boxes in the two design sheets below were the parts that exported after grouping the layers, deleting everything else, and cropping the artboard; the first one was 232x232, the second one was 233x232.

<img width="1792" alt="Image" src="https://github.com/user-attachments/assets/1c103e17-c93c-46ef-9d3f-22042d016c4e" />

<img width="1792" alt="Image" src="https://github.com/user-attachments/assets/4751a2fe-58cf-454f-97d8-9f8a43868f33" />

**Comment by Mario662629** [comment]
Oh, and additionally, one more thing. When exporting an SVG and changing the size (using the Width and Height boxes in the export GUI), the image still gets exported at the original size (rather than scaling it)...

**Comment by photopea** [comment]
I have fixed the last problem that you mentioned.

If you have a different problem, please, describe the steps to see that problem.
