### ISSUE TITLE
When saving as AI, layers cut using the Pathfinder fill in with "<Path>" layers in the shapes of the cutouts.

### ISSUE THREAD

**Issue by Mario662629** [photopea/vectorpea#87]
[ctk-4200_sm.pdf](https://github.com/user-attachments/files/21556460/ctk-4200_sm.pdf)
To see this bug, open this PDF, then save it as AI without making any changes. Open the new AI file, and look at the parts that got filled in.

In addition, saving it as SVG offsets some of the shapes a tiny bit.

**Comment by Mario662629** [comment]
In addition, when saving as PDF after splitting some layers (which can be done by duplicating a the layer and deleting opposite shapes on each one), they sometimes merge back together into one layer (although nothing looks different in the file itself).

**Comment by photopea** [comment]
I have fixed the problem with exporting your PDF file as AI!

When you export a SVG, the coordinates of points are rounded to 1/10 of a pixel, so there could be an error of up to 1/20th of a pixel (from the original coordinate). I think it does not mind in practice.

Elements inside a PDF file are not structured into groups in any way. Photopea merges together as many objects as possible, to keep the number of layers low. But maybe we could do it differently in Vectorpea and keep each object separate.

**Comment by Mario662629** [comment]
OK, this is now partially resolved. However, I will show you the PDF layer merging issue in more detail shortly.

**Comment by photopea** [comment]
I have made Vectorpea work differently. It will not merge layers with the same style anymore, when loading a PDF.

Your original PDF file has about 2x more layers now, when opened in Vectorpea.

**Comment by Mario662629** [comment]
Before (every separate LCD in this diagram is on its own layer):
<img width="1792" height="1077" alt="Image" src="https://github.com/user-attachments/assets/2a35bb4c-57ce-487f-9ae1-c29cec248d0e" />

After (several LCDs merged themselves, you can see the color-coding for the LCD sets that merged):
<img width="1792" height="1077" alt="Image" src="https://github.com/user-attachments/assets/64fc9d15-da75-4e04-8e0f-076d4239223f" />

**Comment by photopea** [comment]
Could you please try all this in the version of Photopea that I have published eight minutes ago?

**Comment by photopea** [comment]
"When merging the two layers in this document, the "4" fills in." - how do you merge layers? Where should I click to see the problem?

**Comment by Mario662629** [comment]
> "When merging the two layers in this document, the "4" fills in." - how do you merge layers? Where should I click to see the problem?

- Select both layers in the right-hand panel.
- Open the Pathfinder.
- Click "Merge".

**Comment by photopea** [comment]
I have fixed the problem with merging shapes with holes. Also, now, Pathfinder will always be in a sidebar, when you open Vectorpea for the first time.

Selecting all layers with Command+V? Is it a well-known shortcut of some software?

**Comment by Mario662629** [comment]
> I have fixed the problem with merging shapes with holes. Also, now, Pathfinder will always be in a sidebar, when you open Vectorpea for the first time.
> 
> Selecting all layers with Command+V? Is it a well-known shortcut of some software?

- I don't know what software has a shortcut for selecting all layers.
- Unlike Photopea, saving a PDF, SVG, etc. in Vectorpea. automatically saves it as AI instead of writing to the original file (if permissions are granted).
- Some object hitboxes are a bit off and clicking in certain areas doesn't select the object, but instead automatically deselects everything even while holding Shift, it especially happens when clicking not in the center of objects. To reproduce, download the file below, change the extension to AI, open it in Vectorpea, zoom in, and click on certain parts of some objects while holding Shift. The file extension was changed during the import because .AI files aren't supported in GitHub comments.
[lcd.txt](https://github.com/user-attachments/files/21582074/lcd.txt)

**Comment by photopea** [comment]
The problem with merging shapes with "holes" should be fixed now. Also, if you open an SVG or a PDF file, pressing Ctrl+S will replace the original file.

**Comment by Mario662629** [comment]
The SVG export offset issue, which you still haven't fixed, is preventing me from creating accurate LCD diagrams in SVG format. This happens even when the PDF is exported to SVG with a multiplied image scale. To reproduce, simply download the PDF below, and rename the extension to AI. Then, open it in Vectorpea, and export it as SVG with a scale of 1000%.
[lcd.pdf](https://github.com/user-attachments/files/22079416/lcd.pdf)

**Comment by photopea** [comment]
I tried to export your PDF file as an SVG at 1000%, but I do not see any issues. Could you share a screenshot and highlight the problem in that screeshot?

**Comment by photopea** [comment]
I can not see your images :( could you check your comment?

**Comment by photopea** [comment]
are you talking about the skewed rectangles, that have edges which are not perfectly parallel?

**Comment by Mario662629** [comment]
It works, but only without "minify" enabled. It would be cool to be able to select which aspects of the SVG to minify and which ones to keep (e.g. keep precision but remove layer names and folders) to keep the file size as small as possible while keeping the precision.
